Add option to use GitHub Attest

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -22,6 +22,10 @@ inputs:
     description: "Turn on to sign EIF and info on ghcr.io registry. (Allowed values: 'true', 'false')"
     required: true
     default: "false"
+  enable-github-attest:
+    description: "Turn on to attest ghcr.io artifact using GitHub attest. (Allowed values: 'true', 'false')"
+    required: true
+    default: "false"
   eif-file-name:
     description: "The EIF file name in the pushed artifact on ghcr. (Required when enable-ghcr-push is true)"
     required: false
@@ -51,7 +55,10 @@ outputs:
   rekor-log-index:
     description: "The Rekor transparency log index of the signing"
     value: ${{ steps.sign-artifact.outputs.log-index || '' }}
-    
+  github-attest-bundle-path:
+    description: "Absolute path to the file containing the attestation generated by GitHub Attest"
+    value: ${{ steps.github-attest.outputs.bundle-path || '' }}
+
 runs:
   using: "composite"
   steps:
@@ -74,6 +81,7 @@ runs:
       env:
         ENABLE_GHCR_PUSH: ${{ inputs.enable-ghcr-push }}
         ENABLE_ARTIFACT_SIGN: ${{ inputs.enable-artifact-sign }}
+        ENABLE_GITHUB_ATTEST: ${{ inputs.enable-github-attest }}
         EIF_FILE_NAME: ${{ inputs.eif-file-name }}
         EIF_INFO_FILE_NAME: ${{ inputs.eif-info-file-name }}
         ARTIFACT_TAG: ${{ inputs.artifact-tag }}
@@ -89,8 +97,18 @@ runs:
           exit 1
         fi
 
+        if [[ "${ENABLE_GITHUB_ATTEST}" != "true" && "${ENABLE_GITHUB_ATTEST}" != "false" ]]; then
+          echo "::error title=⛔ error hint::enable-github-attest should be 'true' or 'false'"
+          exit 1
+        fi
+
         if [[ "${ENABLE_ARTIFACT_SIGN}" == "true" && "${ENABLE_GHCR_PUSH}" != "true" ]]; then
           echo "::error title=⛔ error hint::enable-ghcr-push must be true when enable-artifact-sign is true"
+          exit 1
+        fi
+
+        if [[ "${ENABLE_GITHUB_ATTEST}" == "true" && "${ENABLE_GHCR_PUSH}" != "true" ]]; then
+          echo "::error title=⛔ error hint::enable-ghcr-push must be true when enable-github-attest is true"
           exit 1
         fi
 
@@ -168,16 +186,26 @@ runs:
         DIGEST=$(sha256sum tmp/manifest.json | cut -d " " -f 1)
 
         echo "digest=${DIGEST}" >> "${GITHUB_OUTPUT}"
-        echo "path=ghcr.io/${{ github.repository }}:${ARTIFACT_TAG}@sha256:${DIGEST}" >> "${GITHUB_OUTPUT}"
+        echo "path=ghcr.io/${{ github.repository }}" >> "${GITHUB_OUTPUT}"
+        echo "path-with-digest=ghcr.io/${{ github.repository }}:${ARTIFACT_TAG}@sha256:${DIGEST}" >> "${GITHUB_OUTPUT}"
 
     - name: Sign artifact
       id: sign-artifact
       if: ${{ inputs.enable-artifact-sign == 'true' }}
       shell: bash
       env:
-        ARTIFACT_PATH: ${{ steps.push-file.outputs.path }}
+        ARTIFACT_PATH: ${{ steps.push-file.outputs.path-with-digest }}
       run: |
         RESPONSE=$(cosign sign --yes ${ARTIFACT_PATH} 2>&1)
         echo "${RESPONSE}"
         LOG_INDEX=$(echo "${RESPONSE}" | grep "tlog entry created with index: " | cut -d ":" -f 2 | tr -d " ")
         echo "log-index=${LOG_INDEX}" >> "${GITHUB_OUTPUT}"
+
+    - name: Github attest
+      id: github-attest
+      if: ${{ inputs.enable-github-attest == 'true' }}
+      uses: actions/attest-build-provenance@897ed5eab6ed058a474202017ada7f40bfa52940  # actions/attest-build-provenance@v1.0.0
+      with:
+        subject-name: ${{ steps.push-file.outputs.path }}
+        subject-digest: "sha256:${{ steps.push-file.outputs.digest }}"
+        push-to-registry: true
